import { Demo, ActivityEntry } from "./types";

const DAY = 864e5;
const NOW = Date.now();

export const SEED_DEMOS: Demo[] = [
  { id: 1, date: "2026-04-10", teacher: "Shoaib Ghani", tid: 62, student: "Ahmed Khan", level: "IGCSE", subject: "Mathematics", pour: [{ cat: "Video", desc: "Camera off 10 min" }], review: "Strong methodology but camera issues.", studentRaw: 8, analystRating: 4, status: "Pending", suggestions: "Keep camera on.", agent: "", comments: "", verbatim: "", acctType: "", link: "", marketing: false, ts: NOW - 2 * DAY },
  { id: 2, date: "2026-04-09", teacher: "Nageena Arif", tid: 598, student: "Sara Ali", level: "O Level", subject: "Chemistry", pour: [], review: "Excellent engagement throughout.", studentRaw: 9, analystRating: 5, status: "Pending", suggestions: "Add practice problems.", agent: "", comments: "", verbatim: "", acctType: "", link: "", marketing: false, ts: NOW - 3 * DAY },
  { id: 3, date: "2026-04-08", teacher: "Rizwan Anwer", tid: 90, student: "Hanna Mahmood", level: "A2 Level", subject: "Further Mathematics", pour: [{ cat: "Resources", desc: "No visual aids" }], review: "Good pace, limited whiteboard.", studentRaw: 7, analystRating: 3, status: "Converted", suggestions: "Use whiteboard for proofs.", agent: "Maryam", comments: "Parent impressed. Closed same day.", verbatim: "The teacher was really smart.", acctType: "", link: "", marketing: false, ts: NOW - 4 * DAY },
  { id: 4, date: "2026-04-07", teacher: "Sophia Abid", tid: 107, student: "Omar Raza", level: "IGCSE", subject: "Physics", pour: [{ cat: "Interaction", desc: "One-directional" }, { cat: "Time", desc: "Ended early" }], review: "Rushed and one-directional.", studentRaw: 5, analystRating: 2, status: "Not Converted", suggestions: "Build rapport first.", agent: "Muhammad", comments: "Student found it too fast.", verbatim: "Too fast, did not understand.", acctType: "Product", link: "", marketing: false, ts: NOW - 5 * DAY },
  { id: 5, date: "2026-04-11", teacher: "Inayat Karim", tid: 543, student: "Layla Sheikh", level: "IB", subject: "Biology", pour: [], review: "Very interactive with great examples.", studentRaw: 9, analystRating: 5, status: "Pending", suggestions: "No improvements needed.", agent: "", comments: "", verbatim: "", acctType: "", link: "", marketing: false, ts: NOW - DAY },
  { id: 6, date: "2026-04-08", teacher: "Maryam Imran", tid: 547, student: "Zara Malik", level: "IGCSE", subject: "English", pour: [{ cat: "Interaction", desc: "Did not adapt" }, { cat: "Resources", desc: "Too advanced" }], review: "Prepared but inflexible.", studentRaw: 6, analystRating: 3, status: "Pending", suggestions: "Assess level before preparing.", agent: "", comments: "", verbatim: "", acctType: "", link: "", marketing: false, ts: NOW - 4 * DAY },
  { id: 7, date: "2026-04-06", teacher: "Hira Zafar", tid: 594, student: "Hassan Raza", level: "A Level", subject: "Physics", pour: [{ cat: "Time", desc: "Ended 15 min early" }], review: "Good knowledge, ended early.", studentRaw: 7, analystRating: 4, status: "Pending", suggestions: "Use full session time.", agent: "", comments: "", verbatim: "", acctType: "", link: "", marketing: false, ts: NOW - 6 * DAY },
  { id: 8, date: "2026-04-12", teacher: "Rameesha Saleem", tid: 599, student: "Alina Farooq", level: "A Level", subject: "Economics", pour: [], review: "Excellent demo. Perfect structure.", studentRaw: 10, analystRating: 5, status: "Pending", suggestions: "Use as training example.", agent: "", comments: "", verbatim: "", acctType: "", link: "", marketing: true, ts: NOW },
  { id: 9, date: "2026-03-15", teacher: "Shoaib Ghani", tid: 62, student: "Bilal Ahmed", level: "IGCSE", subject: "Mathematics", pour: [], review: "Solid algebra session.", studentRaw: 8, analystRating: 4, status: "Converted", suggestions: "Add word problems.", agent: "Hoor", comments: "Quick close.", verbatim: "Very patient teacher.", acctType: "", link: "", marketing: false, ts: NOW - 28 * DAY },
  { id: 10, date: "2026-03-10", teacher: "Inayat Karim", tid: 543, student: "Fatima Noor", level: "IB", subject: "Biology", pour: [{ cat: "Technical", desc: "Zoom disconnected" }], review: "Content great when connected.", studentRaw: 6, analystRating: 4, status: "Not Converted", suggestions: "Test connection.", agent: "Maryam", comments: "Chose local tutor.", verbatim: "Internet kept cutting out.", acctType: "Product", link: "", marketing: false, ts: NOW - 33 * DAY },
  { id: 11, date: "2026-03-20", teacher: "Nageena Arif", tid: 598, student: "Amina Shah", level: "IGCSE", subject: "Chemistry", pour: [], review: "Great session.", studentRaw: 9, analystRating: 5, status: "Converted", suggestions: "Continue.", agent: "Muhammad", comments: "Enrolled 3 months.", verbatim: "Loved the style.", acctType: "", link: "", marketing: false, ts: NOW - 23 * DAY },
  { id: 12, date: "2026-03-05", teacher: "Sophia Abid", tid: 107, student: "Tariq Hassan", level: "O Level", subject: "Physics", pour: [{ cat: "Interaction", desc: "No questions" }], review: "Monotone delivery.", studentRaw: 4, analystRating: 2, status: "Not Converted", suggestions: "Style overhaul needed.", agent: "Hoor", comments: "Child was bored.", verbatim: "It was boring.", acctType: "Product", link: "", marketing: false, ts: NOW - 38 * DAY },
];

export const SEED_ACTIVITY: ActivityEntry[] = [
  { id: 1, action: "submitted", user: "Analyst", target: "Alina Farooq demo", time: "2 min ago" },
  { id: 2, action: "converted", user: "Hoor", target: "Bilal Ahmed", time: "1 hour ago" },
  { id: 3, action: "flagged POUR", user: "Analyst", target: "Hassan Raza", time: "3 hours ago" },
];
